version: '3.1'
services:
  db:
    image: postgres:13.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - /opt/pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docker_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    image: drucoder/web-server
    container_name: application
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    volumes:
      - /opt/default.conf:/etc/nginx/conf.d/defaul.conf
    links:
      - app
    ports:
      - 8989:8989
